[tool.poetry]
name = "cd-py-math"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
cd-py-consts = {git = "https://github.com/RulezKT/cd_py_consts.git"}
pytest = "^8.0.2"
